apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyramid-led
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/manifests
    repoURL: https://github.com/sentairanger/pyramid-led
    targetRevision: HEAD
  syncPolicy: {}
